### ISSUE TITLE
How to build the acpioff module?

### ISSUE THREAD

**Issue by darose** [awalls-cx18/syslinux#1]
I'm not able to build the acpioff module.  When I run "make", it builds libacpica.a successfully, but then failed with:

make: *** No rule to make target 'acpioff.c32', needed by 'all'.  Stop.

Am I overlooking something obvious?

**Comment by awalls-cx18** [comment]
The makefile includes the com32.mk file here:
https://github.com/awalls-cx18/syslinux/blob/acpi_off/com32/acpioff/Makefile#L21
which has the proper make targets here:
https://github.com/awalls-cx18/syslinux/blob/acpi_off/mk/com32.mk#L77
https://github.com/awalls-cx18/syslinux/blob/acpi_off/mk/com32.mk#L81
https://github.com/awalls-cx18/syslinux/blob/acpi_off/mk/com32.mk#L96

So you either are missing required development tools (e.g. objcopy), have a path/environment variable problem, or you are not working with the tip of the acpi_off branch as I last left it 4.5 years ago.
(Forward porting to updated versions of syslinux is on you.)

None of these are issues with the code.  Closing.

**Comment by darose** [comment]
Not suggesting there's any issues with the code; just trying to get it to build.

I was building only the directory com32/acpioff, and not building from the root of the tree.  And I was building off of a download of your branch (https://github.com/awalls-cx18/syslinux/archive/acpi_off.zip).

I.e.:
$ wget https://github.com/awalls-cx18/syslinux/archive/acpi_off.zip
$ unzip acpi_off.zip
$ cd syslinux-acpi_off/com32/acpioff
$ make

Perhaps I'm missing a dependency - I'll check.  Or if you should happen to see any other reasons why this might not build, I'd welcome suggestions.

**Comment by awalls-cx18** [comment]
On December 14, 2016 3:30:19 PM EST, darose <notifications@github.com> wrote:
>Not suggesting there's any issues with the code; just trying to get it
>to build.
>
>I was building only the directory com32/acpioff, and not building from
>the root of the tree.  And I was building off of a download of your
>branch (https://github.com/awalls-cx18/syslinux/archive/acpi_off.zip).
>
>I.e.:
>$ wget https://github.com/awalls-cx18/syslinux/archive/acpi_off.zip
>$ unzip acpi_off.zip
>$ cd syslinux-acpi_off/com32/acpioff
>$ make
>
>Perhaps I'm missing a dependency - I'll check.  Or if you should happen
>to see any other reasons why this might not build, I'd welcome
>suggestions.

Build all of syslinux following the normal syslinux build instructions in the repo.

I did not rework any of the syslinux build system.  IIRC doesn't let you just build a single com32 module.  Plus you'll need some of the other libraries in the syslinux tree to link against anyway.

**Comment by tafaust** [comment]
@awalls-cx18 First of, thanks for the effort providing us with an acpi compatible poweroff!
I am experiencing the exact same issue on `syslinux 6.04  Copyright 1994-2015 H. Peter Anvin et al`; cloned through `git clone --recursive git@github.com:awalls-cx18/syslinux.git && git switch acpi_off`; I tried to `make` in the syslinux root dir and end up with 

```
make[1]: Entering directory '/home/domac/temp/syslinux/com32'
set -e; for d in libupload tools lib gpllib libutil modules mboot menu samples rosh cmenu hdt gfxboot sysdump lua/src acpioff; do make -C $d all; done
make[2]: Entering directory '/home/domac/temp/syslinux/com32/libupload'
gcc -Wp,-MT,upload_tftp.o,-MD,./.upload_tftp.o.d -std=gnu99 -m32 -fno-stack-protector -fwrapv -freg-struct-return -mregparm=3 -DREGPARM=3 -march=i386 -Os -fPIE -fno-exceptions -fno-asynchronous-unwind-tables -fno-strict-aliasing -falign-functions=0 -falign-jumps=0 -falign-labels=0 -falign-loops=0 -mpreferred-stack-boundary=2 -W -Wall -Wstrict-prototypes -Wno-clobbered -Werror -march=i386 -fomit-frame-pointer -D__COM32__ -nostdinc -iwithprefix include -I../../com32/libutil/include -I../../com32/include -I../../com32/gplinclude -c -o upload_tftp.o upload_tftp.c
upload_tftp.c: In function ‘upload_tftp_write’:
upload_tftp.c:150:27: error: ‘tftp.srv_ip’ is used uninitialized in this function [-Werror=uninitialized]
  150 |     tftp.srv_gw   = ((tftp.srv_ip ^ tftp.my_ip) & sdi->pxe.ipinfo->netmask)
      |                       ~~~~^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [../../mk/com32.mk:78: upload_tftp.o] Error 1
make[2]: Leaving directory '/home/domac/temp/syslinux/com32/libupload'
make[1]: *** [Makefile:5: all] Error 2
make[1]: Leaving directory '/home/domac/temp/syslinux/com32'
make: *** [Makefile:89: all] Error 2
```

Any hints please?

----
EDIT: Okay, sorry, it seems that the `Makefile` change by a lot... this patch is probably incompatible with syslinux 6.04.

**Comment by awalls-cx18** [comment]
First, just try building the tip acpi_off branch of this repo without modification.  It should work just fine.

Second, don't use the '-Werror' compiler flag unless you are prepared to fix every compiler warning in the SYSLINUX codebase that was the basis of this repo. (From Feb 2012)

Porting forward to another version of SYSLINUX should be straightforward, since the ACPI stuff is fairly isolated, but it could still be a bit of work.

**Comment by awalls-cx18** [comment]
@tahesse Actually you probably have to comment out this line:

https://github.com/awalls-cx18/syslinux/blob/acpi_off/mk/syslinux.mk#L82

to prevent the '-Werror' flag from being set during compile.

Edit:
And you have to run 'make' twice at the top level, due to some ordering error in the build regarding the ordering of building the acpia and the acpioff.c32 module. :(

And, it still fails in syslinux/lzo due to some macro expansion that modifies some array '__acc_cta' in a way that modern compilers flag as an error. :(

What a mess.  I guess 8 years of neglect has consequences.

**Comment by awalls-cx18** [comment]
@tahesse Build ordering problem fixed with this commit:

https://github.com/awalls-cx18/syslinux/commit/2ddabb1ed77454a36071200abb5f430ae01038d4

but the build is still broken due to the LZO stuff, at the moment.

**Comment by awalls-cx18** [comment]
@tahesse I've pushed changes so that the acpi_off branch builds on a somewhat modern Fedora 30 system again.  I haven't tested it operationally.  The warnings seem a bit disconcerting.

The real fix would be to port everything forward to be based off of the latest SYSLINUX.
Everything that would need to be ported is under the com32/acpioff directory,
and the one change to the com32/Makefile.

**Comment by CpServiceSpb** [comment]
I tried to build  syslinux-6.04~git20190206.bf6db5b4 version with acpioff downloaded from here.
I made changes to Makefile of com32.
And there is an error: "*** No rule to make target 'acpioff.o', needed by 'acpioff.elf'.  Stop."

As I think it is connected with inaccessibility of ../../mk/com32.mk and the syslinux.mk.

**Comment by tafaust** [comment]
Let me check it too on the weekend or if I can make some time for it. I'll update this post.
